package com.cryptochief.processing

import com.cryptochief.processing.http.RequestSigner
import com.cryptochief.processing.webhook.WebhookHeadersException
import com.cryptochief.processing.webhook.WebhookSignatureException
import com.cryptochief.processing.webhook.WebhookTimestampException
import com.cryptochief.processing.webhook.WebhookVerificationException
import com.cryptochief.processing.webhook.WebhookVerifier
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestFactory
import java.security.MessageDigest
import java.time.Instant
import java.util.Base64
import kotlin.time.Duration.Companion.seconds

/** Vectors in `src/test/resources/webhook_hmac_v1_vectors.json` are generated by the webhook service. */
class WebhookV1VectorsTest {

    private class Vector(val json: JsonObject) {
        val name = str("name")
        val apiKey = str("api_key")
        val timestamp = json.getValue("timestamp").jsonPrimitive.long
        val deliveryId = str("delivery_id")
        val body: ByteArray = json["body_base64"]?.let { Base64.getDecoder().decode(it.jsonPrimitive.content) }
            ?: str("body").toByteArray(Charsets.UTF_8)
        val now: Instant = Instant.ofEpochSecond(json.getValue("now").jsonPrimitive.long)
        val expect = str("expect")

        /** Header values the receiver sees: defaults from the record, replaced by `headers`. */
        val headers: Map<String, List<String>> = buildMap {
            put(WebhookVerifier.TIMESTAMP_HEADER, listOf(timestamp.toString()))
            put(WebhookVerifier.DELIVERY_HEADER, listOf(deliveryId))
            put(WebhookVerifier.SIGNATURE_HEADER, listOf(str("signature")))
            json["headers"]?.jsonObject?.forEach { (name, values) ->
                put(name, values.jsonArray.map { it.jsonPrimitive.content })
            }
        }

        fun str(field: String): String = json.getValue(field).jsonPrimitive.content
    }

    private val vectors: List<Vector> = run {
        val bytes = checkNotNull(javaClass.getResourceAsStream("/webhook_hmac_v1_vectors.json")) {
            "webhook_hmac_v1_vectors.json not found"
        }.use { it.readBytes() }
        assertEquals(
            "15a6e1423708e8c3b9ec4fac7ee6eb383db56703605647e02308a29166722502",
            MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) },
        )
        Json.parseToJsonElement(bytes.toString(Charsets.UTF_8)).jsonArray.map { Vector(it.jsonObject) }
    }

    private fun outcome(block: () -> Unit): String = try {
        block()
        "ok"
    } catch (e: WebhookVerificationException) {
        when (e) {
            is WebhookHeadersException -> "bad_headers"
            is WebhookTimestampException -> "timestamp_out_of_range"
            is WebhookSignatureException -> "bad_signature"
        }
    }

    @Test
    fun `vector file has every kind of outcome`() {
        assertEquals(54, vectors.size)
        assertEquals(
            mapOf("ok" to 22, "bad_headers" to 26, "bad_signature" to 4, "timestamp_out_of_range" to 2),
            vectors.groupingBy { it.expect }.eachCount(),
        )
    }

    @TestFactory
    fun `string to sign and signature match the webhook service`(): List<DynamicTest> = vectors.map { v ->
        DynamicTest.dynamicTest(v.name) {
            assertEquals(v.str("body_sha256"), RequestSigner.bodySha256(v.body))
            assertEquals(v.str("string_to_sign"), RequestSigner.webhookV1StringToSign(v.timestamp, v.deliveryId, v.body))
            assertEquals(v.str("signature"), RequestSigner.signWebhookV1(v.apiKey, v.timestamp, v.deliveryId, v.body))
        }
    }

    @TestFactory
    fun `verify with a header map gives the expected outcome`(): List<DynamicTest> = vectors.map { v ->
        DynamicTest.dynamicTest(v.name) {
            assertEquals(v.expect, outcome { WebhookVerifier.verify(v.apiKey, v.body, v.headers, 300.seconds) { v.now } })
            // Header names in another case.
            val lower = v.headers.mapKeys { it.key.lowercase() }
            assertEquals(v.expect, outcome { WebhookVerifier.verify(v.apiKey, v.body, lower, 300.seconds) { v.now } })
        }
    }

    @TestFactory
    fun `verify with a header function gives the expected outcome`(): List<DynamicTest> =
        vectors.filter { v -> v.headers.values.none { it.size > 1 } }.map { v ->
            DynamicTest.dynamicTest(v.name) {
                val header = { name: String -> v.headers[name]?.firstOrNull() }
                assertEquals(v.expect, outcome { WebhookVerifier.verify(v.apiKey, v.body, header, 300.seconds) { v.now } })
            }
        }

    @Test
    fun `the same value under two spellings of a name is a repeat`() {
        val v = vectors.first { it.name == "payout_paid" }
        val headers = v.headers + ("x-cc-signature" to listOf(v.str("signature")))
        assertEquals("bad_headers", outcome { WebhookVerifier.verify(v.apiKey, v.body, headers, 300.seconds) { v.now } })
        assertTrue(outcome { WebhookVerifier.verify(v.apiKey, v.body, v.headers, 300.seconds) { v.now } } == "ok")
    }
}
